import { useSession } from "next-auth/react";
import React from "react";
import Nav from "@/components/nav";
import Link from "next/link";
import Head from "next/head";
import {
  Box,
  Container,
  Typography,
  TextField,
  Button,
  Stack,
} from "@mui/material";

export default function CreateARecipeForm() {
  const { data: session, status } = useSession();

  if (status === "authenticated") {
    return (
      <>
        <Head>
          <title>Creating a Recipe</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Nav />
        <Box sx={{ marginTop: "120px", marginLeft: 2 }}>
          <form>
            <Box sx={{ width: 550, height: 400, bgcolor: "red" }}>
              Burger
              <Box sx={{ marginLeft: 100, bottom: 800 }}>
                <TextField
                  sx={{ marginTop: 3, width: 300 }}
                  required
                  id="outlined-basic"
                  label="Prep Time"
                  variant="outlined"
                  placeholder="Ex: 10"
                />
                <TextField
                  sx={{ marginTop: 3, width: 300 }}
                  required
                  id="outlined-basic"
                  label="Cook Time"
                  variant="outlined"
                  placeholder="Ex: 10"
                />
                <TextField
                  sx={{ marginTop: 3, width: 300 }}
                  required
                  id="outlined-basic"
                  label="Total Time"
                  variant="outlined"
                  placeholder="Cook Time + Prep Time"
                />
                <TextField
                  sx={{ marginTop: 3, width: 300 }}
                  required
                  id="outlined-multiline-static"
                  label="Ingredients"
                  multiline
                  rows={4}
                />
                <TextField
                  sx={{ marginTop: 3, width: 300 }}
                  required
                  id="outlined-multiline-static"
                  label="Directions"
                  multiline
                  rows={4}
                />
              </Box>
            </Box>
            <Box sx={{ width: { sm: 1, md: 200 } }}>
              <TextField
                sx={{ marginTop: 3, width: 300 }}
                required
                id="outlined-basic"
                label="title"
                variant="outlined"
              />
              <TextField
                sx={{ marginTop: 3, width: 300 }}
                required
                id="outlined-multiline-static"
                label="Discription"
                multiline
                rows={3}
                placeholder="Discription of the recipe"
              />
            </Box>
            <Stack sx={{ marginLeft: 114 }} direction="row" spacing={2}>
              <Button Size="medium" variant="contained">
                Cancel{" "}
              </Button>
              <Button size="medium" variant="contained">
                Submit
              </Button>
            </Stack>
          </form>
        </Box>
      </>
    );
  }

  return (
    <>
      <Head>
        <title>Creating a Recipe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Container
        sx={{
          marginTop: "400px",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <Typography variant="h2">
          To access this page please{" "}
          <Link href="/api/auth/signin">Sign In</Link>
        </Typography>
      </Container>
    </>
  );
}
