import { useSession } from "next-auth/react";
import React from "react";
import Nav from "@/components/nav";
import Link from "next/link";
import Head from "next/head";
import {
  Box,
  Container,
  Typography,
  TextField,
  Button,
  Stack,
} from "@mui/material";

export default function CreateARecipeForm() {
  const { data: session, status } = useSession();

  if (status === "authenticated") {
    return (
      <>
        <Head>
          <title>Creating a Recipe</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Nav />
        <Box sx={{ mt: "120px", marginLeft: 2 }}>
          <form>
            <Box sx={{ width: 550, height: 400, bgcolor: "red" }}>
              Burger
              {/* Container for title and Description */}
              <Box sx={{ ml: 100}}>
                {/* TextField for Title */}
                <TextField
                  sx={{ width: 300 }}
                  required
                  id="outlined-basic"
                  label="title"
                  variant="outlined"
                />
                {/* TextField for Description */}
                <TextField
                  sx={{ mt: 3, width: 400 }}
                  required
                  id="outlined-multiline-static"
                  label="Description"
                  multiline
                  rows={3}
                  placeholder="Description of the recipe"
                />
                <TextField
                  sx={{ mt: 3, width: 150 }}
                  required
                  id="outlined-basic"
                  label="Prep Time"
                  variant="outlined"
                  placeholder="Ex: 10"
                />
                <TextField
                  sx={{ mt: 3, width: 150 }}
                  required
                  id="outlined-basic"
                  label="Cook Time"
                  variant="outlined"
                  placeholder="Ex: 10"
                />
                <TextField
                  sx={{ mt: 3, width: 150 }}
                  required
                  id="outlined-basic"
                  label="Total Time"
                  variant="outlined"
                  placeholder="Total time"
                />
              </Box>
            </Box>
            <Box sx={{ display: "flex", flexDirection: "row", gap: 2, mt: 5 }}>
              {/* TextField for Ingredients */}
              <TextField
                sx={{ mt: 3, width: 450 }}
                required
                id="outlined-multiline-static"
                label="Ingredients"
                multiline
                rows={4}
              />
              {/* TextField for Directions */}
              <TextField
                sx={{ mt: 3, width: 450 }}
                required
                id="outlined-multiline-static"
                label="Directions"
                multiline
                rows={4}
              />
            </Box>
            <Stack sx={{ m: 1 }} direction="row" spacing={2}>
              <Button size="medium" variant="contained">
                Submit
              </Button>
              <Button Size="medium" variant="contained">
                Cancel{" "}
              </Button>
            </Stack>
          </form>
        </Box>
      </>
    );
  }

  return (
    <>
      <Head>
        <title>Creating a Recipe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Container
        sx={{
          mt: "450px",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <Typography variant="h2">
          To access this page please{" "}
          <Link href="/api/auth/signin">Sign In</Link>
        </Typography>
      </Container>
    </>
  );
}
